export const friends = [
  {
    name: 'Tanvir Ahmed',
    email: 'tanvir@gmail.com',
    friends: '930',
    posts: '87',
    followers: '1.2k',
  },
  {
    name: 'Nayeem Hasan',
    email: 'nayeem@gmail.com',
    friends: '450',
    posts: '42',
    followers: '900',
  },
  {
    name: 'Mehedi Hasan',
    email: 'mehedi@gmail.com',
    friends: '780',
    posts: '55',
    followers: '1.5k',
  },
  {
    name: 'Rafiul Islam',
    email: 'rafiul@gmail.com',
    friends: '1023',
    posts: '122',
    followers: '2.3k',
  },
  {
    name: 'Sadia Afrin',
    email: 'sadia@gmail.com',
    friends: '389',
    posts: '33',
    followers: '670',
  },
  {
    name: 'Ashik Mahmud',
    email: 'ashik@gmail.com',
    friends: '560',
    posts: '40',
    followers: '740',
  },
  {
    name: 'Mim Akter',
    email: 'mim@gmail.com',
    friends: '820',
    posts: '66',
    followers: '1k',
  },
  {
    name: 'Shuvo Roy',
    email: 'shuvo@gmail.com',
    friends: '910',
    posts: '99',
    followers: '1.7k',
  },
  {
    name: 'Tushar Khan',
    email: 'tushar@gmail.com',
    friends: '1120',
    posts: '188',
    followers: '3.2k',
  },
  {
    name: 'Rafi Khan',
    email: 'rafik@gmail.com',
    friends: '350',
    posts: '28',
    followers: '530',
  },
  {
    name: 'Hasan Mahmud',
    email: 'hasan@gmail.com',
    friends: '670',
    posts: '73',
    followers: '1.1k',
  },
  {
    name: 'Sumi Akter',
    email: 'sumi@gmail.com',
    friends: '500',
    posts: '44',
    followers: '880',
  },
  {
    name: 'Ariyan Rahman',
    email: 'ariyan@gmail.com',
    friends: '920',
    posts: '112',
    followers: '2k',
  },
  {
    name: 'Rabbi Hossain',
    email: 'rabbi@gmail.com',
    friends: '430',
    posts: '39',
    followers: '760',
  },
  {
    name: 'Rima Chowdhury',
    email: 'rima@gmail.com',
    friends: '890',
    posts: '67',
    followers: '1.4k',
  },
  {
    name: 'Zarif Hossain',
    email: 'zarif@gmail.com',
    friends: '1012',
    posts: '98',
    followers: '1.9k',
  },
  {
    name: 'Fahim Islam',
    email: 'fahim@gmail.com',
    friends: '600',
    posts: '51',
    followers: '970',
  },
  {
    name: 'Jannat Mawa',
    email: 'jannat@gmail.com',
    friends: '490',
    posts: '29',
    followers: '690',
  },
  {
    name: 'Tahmid Hasan',
    email: 'tahmid@gmail.com',
    friends: '870',
    posts: '86',
    followers: '1.3k',
  },
  {
    name: 'Rashed Khan',
    email: 'rashed@gmail.com',
    friends: '740',
    posts: '70',
    followers: '1.1k',
  },
  {
    name: 'Sakib Rahman',
    email: 'sakib@gmail.com',
    friends: '970',
    posts: '107',
    followers: '1.8k',
  },
  {
    name: 'Oishee Akter',
    email: 'oishee@gmail.com',
    friends: '660',
    posts: '43',
    followers: '950',
  },
  {
    name: 'Anika Tabassum',
    email: 'anika@gmail.com',
    friends: '880',
    posts: '99',
    followers: '1.5k',
  },
  {
    name: 'Aminul Islam',
    email: 'aminul@gmail.com',
    friends: '390',
    posts: '31',
    followers: '600',
  },
  {
    name: 'Sajib Ahmed',
    email: 'sajib@gmail.com',
    friends: '1080',
    posts: '140',
    followers: '2.7k',
  },
  {
    name: 'Mahin Sarker',
    email: 'mahin@gmail.com',
    friends: '430',
    posts: '35',
    followers: '700',
  },
  {
    name: 'Sumaiya Jahan',
    email: 'sumaiya@gmail.com',
    friends: '740',
    posts: '65',
    followers: '1.2k',
  },
  {
    name: 'Borno Chakma',
    email: 'borno@gmail.com',
    friends: '950',
    posts: '102',
    followers: '1.9k',
  },
  {
    name: 'Yasir Arafat',
    email: 'yasir@gmail.com',
    friends: '510',
    posts: '49',
    followers: '850',
  },
  {
    name: 'Rahat Hossain',
    email: 'rahat@gmail.com',
    friends: '690',
    posts: '54',
    followers: '1.1k',
  },
  {
    name: 'Rafiq Mia',
    email: 'rafiq.mia@hotmail.com',
    friends: '959',
    posts: '63',
    followers: '8k',
  },
  {
    name: 'Noman Chowdhury',
    email: 'noman.chowdhury@yahoo.com',
    friends: '496',
    posts: '111',
    followers: '808',
  },
  {
    name: 'Jahid Khan',
    email: 'jahid.khan@gmail.com',
    friends: '1036',
    posts: '213',
    followers: '786',
  },
  {
    name: 'Rafiq Hossain',
    email: 'rafiq.hossain@yahoo.com',
    friends: '682',
    posts: '116',
    followers: '709',
  },
  {
    name: 'Shawon Ahmed',
    email: 'shawon.ahmed@hotmail.com',
    friends: '271',
    posts: '96',
    followers: '1.2k',
  },
  {
    name: 'Shawon Bhuiyan',
    email: 'shawon.bhuiyan@gmail.com',
    friends: '327',
    posts: '9',
    followers: '692',
  },
  {
    name: 'Jahid Bhuiyan',
    email: 'jahid.bhuiyan@yahoo.com',
    friends: '731',
    posts: '260',
    followers: '695',
  },
  {
    name: 'Masud Hasan',
    email: 'masud.hasan@yahoo.com',
    friends: '928',
    posts: '67',
    followers: '923',
  },
  {
    name: 'Rana Uddin',
    email: 'rana.uddin@yahoo.com',
    friends: '284',
    posts: '60',
    followers: '836',
  },
  {
    name: 'Rafiq Hossain',
    email: 'rafiq.hossain@outlook.com',
    friends: '253',
    posts: '87',
    followers: '1.5k',
  },
  {
    name: 'Rafiq Chowdhury',
    email: 'rafiq.chowdhury@outlook.com',
    friends: '890',
    posts: '238',
    followers: '802',
  },
  {
    name: 'Jahid Rahman',
    email: 'jahid.rahman@gmail.com',
    friends: '956',
    posts: '262',
    followers: '648',
  },
  {
    name: 'Sakib Mia',
    email: 'sakib.mia@outlook.com',
    friends: '1375',
    posts: '45',
    followers: '2.7k',
  },
  {
    name: 'Shawon Khan',
    email: 'shawon.khan@gmail.com',
    friends: '637',
    posts: '298',
    followers: '648',
  },
  {
    name: 'Sakib Bhuiyan',
    email: 'sakib.bhuiyan@hotmail.com',
    friends: '570',
    posts: '6',
    followers: '825',
  },
  {
    name: 'Noman Mia',
    email: 'noman.mia@hotmail.com',
    friends: '1015',
    posts: '32',
    followers: '988',
  },
  {
    name: 'Rana Bhuiyan',
    email: 'rana.bhuiyan@hotmail.com',
    friends: '1226',
    posts: '123',
    followers: '906',
  },
  {
    name: 'Sabbir Mia',
    email: 'sabbir.mia@outlook.com',
    friends: '394',
    posts: '173',
    followers: '718',
  },
  {
    name: 'Noman Chowdhury',
    email: 'noman.chowdhury@outlook.com',
    friends: '184',
    posts: '145',
    followers: '578',
  },
  {
    name: 'Shawon Hasan',
    email: 'shawon.hasan@yahoo.com',
    friends: '387',
    posts: '132',
    followers: '969',
  },
  {
    name: 'Shawon Khan',
    email: 'shawon.khan@gmail.com',
    friends: '1018',
    posts: '222',
    followers: '708',
  },
  {
    name: 'Shawon Khan',
    email: 'shawon.khan@hotmail.com',
    friends: '1106',
    posts: '285',
    followers: '757',
  },
  {
    name: 'Rafiq Hasan',
    email: 'rafiq.hasan@outlook.com',
    friends: '321',
    posts: '235',
    followers: '705',
  },
  {
    name: 'Rana Hasan',
    email: 'rana.hasan@yahoo.com',
    friends: '1467',
    posts: '213',
    followers: '768',
  },
  {
    name: 'Shawon Khan',
    email: 'shawon.khan@gmail.com',
    friends: '1453',
    posts: '134',
    followers: '3.8k',
  },
  {
    name: 'Rana Khan',
    email: 'rana.khan@yahoo.com',
    friends: '1479',
    posts: '177',
    followers: '2.4k',
  },
  {
    name: 'Jahid Rahman',
    email: 'jahid.rahman@outlook.com',
    friends: '432',
    posts: '132',
    followers: '985',
  },
  {
    name: 'Shawon Khan',
    email: 'shawon.khan@hotmail.com',
    friends: '276',
    posts: '21',
    followers: '6.6k',
  },
  {
    name: 'Noman Mia',
    email: 'noman.mia@outlook.com',
    friends: '61',
    posts: '14',
    followers: '546',
  },
  {
    name: 'Rafiq Mia',
    email: 'rafiq.mia@outlook.com',
    friends: '491',
    posts: '151',
    followers: '958',
  },
];
